# Generated by Django 2.2.4 on 2019-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('numero_horas', models.IntegerField()),
                ('nota', models.CharField(max_length=40)),
                ('incidencias', models.CharField(max_length=60)),
                ('alumnos', models.ForeignKey(blank=True, null=True, on_delete=True, to='alumnos.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('poblacion', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.CharField(max_length=40)),
                ('codigo_postal', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('asignaturas', models.ForeignKey(blank=True, null=True, on_delete=True, to='maestros.Asignatura')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=True, to='maestros.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('piso', models.IntegerField()),
                ('numero_pupitres', models.IntegerField()),
                ('asignaturas', models.ForeignKey(blank=True, null=True, on_delete=True, to='maestros.Asignatura')),
            ],
        ),
    ]
