# Generated by Django 2.2.4 on 2019-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('poblacion', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.CharField(max_length=40)),
                ('codigo_postal', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
